import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

import { cards, type CardSeed } from '../../data/cards.js';

function sqlValue(value: string | number | boolean | null): string {
  if (value === null) {
    return 'NULL';
  }

  if (typeof value === 'number') {
    if (!Number.isFinite(value)) {
      throw new Error(`Invalid numeric SQL value: ${value}`);
    }

    return String(value);
  }

  if (typeof value === 'boolean') {
    return value ? '1' : '0';
  }

  return `'${value.replaceAll("'", "''")}'`;
}

function validateCard(card: CardSeed, index: number): void {
  const position = index + 1;

  if (!card.name.trim()) {
    throw new Error(`Card ${position} has no name.`);
  }

  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(card.slug)) {
    throw new Error(`Card ${position} has an invalid slug: ${card.slug}`);
  }

  if (!card.cardNumber.trim()) {
    throw new Error(`Card ${position} has no card number.`);
  }

  if (!Number.isInteger(card.cost) || card.cost < 0) {
    throw new Error(`Card ${position} has an invalid cost.`);
  }

  if (!Array.isArray(card.color)) {
    throw new Error(`Card ${position} color must be an array.`);
  }
}

function buildUpsert(card: CardSeed): string {
  const values = {
    name: card.name.trim(),
    slug: card.slug.trim(),
    cardNumber: card.cardNumber.trim(),
    cost: card.cost,
    type: card.type.trim(),
    subtype: card.subtype?.trim() || null,
    rarity: card.rarity.trim(),
    attack: card.attack ?? null,
    health: card.health ?? null,
    rulesText: card.rulesText,
    setCode: card.setCode?.trim() || 'FTB',
    imageUrl: card.imageUrl?.trim() || null,
    color: JSON.stringify(card.color),
    keywords: card.keywords?.trim() || '',
    isUnique: card.isUnique ?? false,
    deckLimit: card.deckLimit ?? null,
  };

  return `
INSERT INTO "Card" (
  "name",
  "slug",
  "cardNumber",
  "cost",
  "type",
  "subtype",
  "rarity",
  "attack",
  "health",
  "rulesText",
  "setCode",
  "imageUrl",
  "color",
  "keywords",
  "isUnique",
  "deckLimit"
)
VALUES (
  ${sqlValue(values.name)},
  ${sqlValue(values.slug)},
  ${sqlValue(values.cardNumber)},
  ${sqlValue(values.cost)},
  ${sqlValue(values.type)},
  ${sqlValue(values.subtype)},
  ${sqlValue(values.rarity)},
  ${sqlValue(values.attack)},
  ${sqlValue(values.health)},
  ${sqlValue(values.rulesText)},
  ${sqlValue(values.setCode)},
  ${sqlValue(values.imageUrl)},
  ${sqlValue(values.color)},
  ${sqlValue(values.keywords)},
  ${sqlValue(values.isUnique)},
  ${sqlValue(values.deckLimit)}
)
ON CONFLICT("slug") DO UPDATE SET
  "name" = excluded."name",
  "cardNumber" = excluded."cardNumber",
  "cost" = excluded."cost",
  "type" = excluded."type",
  "subtype" = excluded."subtype",
  "rarity" = excluded."rarity",
  "attack" = excluded."attack",
  "health" = excluded."health",
  "rulesText" = excluded."rulesText",
  "setCode" = excluded."setCode",
  "imageUrl" = excluded."imageUrl",
  "color" = excluded."color",
  "keywords" = excluded."keywords",
  "isUnique" = excluded."isUnique",
  "deckLimit" = excluded."deckLimit",
  "updatedAt" = CURRENT_TIMESTAMP;
`.trim();
}

async function main(): Promise<void> {
  const seenSlugs = new Set<string>();
  const seenNumbers = new Set<string>();

  cards.forEach((card, index) => {
    validateCard(card, index);

    if (seenSlugs.has(card.slug)) {
      throw new Error(`Duplicate card slug: ${card.slug}`);
    }

    if (seenNumbers.has(card.cardNumber)) {
      throw new Error(`Duplicate card number: ${card.cardNumber}`);
    }

    seenSlugs.add(card.slug);
    seenNumbers.add(card.cardNumber);
  });

  const sql = [
    'PRAGMA foreign_keys = ON;',
    '',
    '-- Generated from data/cards.ts. Do not edit this file manually.',
    '',
    ...cards.map(buildUpsert),
    '',
  ].join('\n\n');

  const outputDirectory = resolve('generated');
  const outputFile = resolve(outputDirectory, 'cards.sql');

  await mkdir(outputDirectory, { recursive: true });
  await writeFile(outputFile, sql, 'utf8');

  console.log(`Generated ${cards.length} cards at ${outputFile}`);
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});